---
title: "Scheme of the simulation pipeline"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pipeline-scheme}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.height=8}
library(erahumed)
library(visNetwork)

layers_docs <- erahumed_docs("layers")

add_node <- function(
    nodes_df,
    id,
    label,
    group = c("layer", "parameter"),
    shape = "box",
    font = list(size = 14),
    x = NA,
    y = NA,
    fixed = FALSE,
    title = ""
) {
  group <- match.arg(group)
  new_node <- data.frame(id, label, group, shape, font, x, y, fixed, title)
  rbind(nodes_df, new_node)
}


add_edge <- function(edges_df, from, to, arrows) {
  rbind(edges_df, data.frame(from = from, to = to, arrows = arrows))
}


# Create ERAHUMED graph
create_erahumed_graph <- function() {
  layers_docs <- erahumed_docs("layers")
  
  nodes_df <- data.frame()
  edges_df <- data.frame()
  
  for (i in seq_along(layers_docs)) {
    layer_id <- layer_name <- names(layers_docs)[[i]]
    layer_web_url <- paste0("https://erahumed.github.io/erahumed/reference/", 
                            layer_name, ".html")
    
    layer_title <- paste0('<p>',
                          '<a href="', layer_web_url, '" target="_blank">', 
                          toupper(layer_name), '</a>',
                          ': ', layers_docs [[ i ]] [["title"]], '</p>'
                          )
    
    y <- 100 * (i - 1)
    
    # Add layer node
    nodes_df <- nodes_df |> add_node(id = layer_id,
                                     label = toupper(layer_name),
                                     group = "layer",
                                     x = 0,
                                     y = 100 * (i - 1),
                                     fixed = TRUE,
                                     title = layer_title
                                     )
    
    # Add link to previous layer
    if (i > 1) {
      dep_id <- names(layers_docs)[[i - 1]]
      edges_df <- edges_df |> add_edge(from = dep_id, 
                                       to = layer_id, 
                                       arrows = "to")
    }
    
    params_docs <- layers_docs[[i]][["parameters"]]
    for (j in seq_along(params_docs)) {
      param_name <- names(params_docs)[[j]]
      param_id <- paste(layer_name, param_name, sep = "-")
      param_title <- paste0("**`[", params_docs[[j]] [["type"]], "]`**:\n",
                            params_docs [[j]] [["description"]]
                            ) |>   
        gsub("\\\\link(?:\\[[^]]+\\])?\\{([^}]+)\\}", "`\\1`", x = _) |>
        shiny::markdown()
      
      nodes_df <- nodes_df |> add_node(id = param_id,
                                       label = param_name,
                                       group = "parameter",
                                       shape = "box",
                                       font = list(size = 14),
                                       x = NA,
                                       y = NA,
                                       fixed = FALSE,
                                       title = param_title)
      edges_df <- edges_df |> add_edge(from = param_id, 
                                       to = layer_name, 
                                       arrows = "none")
    }
  }

  g <- visNetwork(nodes_df, edges_df, width = "100%") |>
    visOptions(highlightNearest = list(enabled = TRUE,
                                       degree = list(from = 1, to = 1),
                                       algorithm = "hierarchical",
                                       labelOnly = FALSE
                                       )
    ) |>
    visPhysics(stabilization = TRUE)

  g
}

# Generate and render the graph
create_erahumed_graph()
```
